# Generated by Django 5.2.6 on 2025-09-24 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.CharField(max_length=100)),
                ('destination', models.CharField(max_length=100)),
                ('optional_stops', models.TextField(blank=True, null=True)),
                ('fare', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
