# Generated by Django 5.2.6 on 2025-10-13 16:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.CharField(max_length=255)),
                ('destination', models.CharField(max_length=255)),
                ('origin_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('origin_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('destination_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('destination_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('transport_type', models.CharField(choices=[('Jeepney', 'Jeepney'), ('Bus', 'Bus'), ('Taxi', 'Taxi'), ('Motorcycle', 'Motorcycle')], default='Jeepney', max_length=50)),
                ('code', models.CharField(blank=True, choices=[('01A', '01A'), ('01B', '01B'), ('01C', '01C'), ('01K', '01K'), ('02A', '02A'), ('02B', '02B'), ('03A', '03A'), ('03B', '03B'), ('03G', '03G'), ('03L', '03L'), ('03Q', '03Q'), ('04B', '04B'), ('04C', '04C'), ('04D', '04D'), ('04H', '04H'), ('04I', '04I'), ('04L', '04L'), ('04M', '04M'), ('06A', '06A'), ('06B', '06B'), ('06C', '06C'), ('06F', '06F'), ('06G', '06G'), ('06H', '06H'), ('07B', '07B'), ('07D', '07D'), ('08F', '08F'), ('08G', '08G'), ('09C', '09C'), ('09F', '09F'), ('09G', '09G'), ('10C', '10C'), ('10E', '10E'), ('10F', '10F'), ('10G', '10G'), ('10H', '10H'), ('10K', '10K'), ('10M', '10M'), ('11A', '11A'), ('11D', '11D'), ('12A', '12A'), ('12B', '12B'), ('12C', '12C'), ('12D', '12D'), ('12F', '12F'), ('12G', '12G'), ('12I', '12I'), ('12J', '12J'), ('12L', '12L'), ('13B', '13B'), ('13C', '13C'), ('13H', '13H'), ('14D', '14D'), ('15', '15'), ('17B', '17B'), ('17C', '17C'), ('17D', '17D'), ('20A', '20A'), ('20B', '20B'), ('21A', '21A'), ('21D', '21D'), ('22A', '22A'), ('22I', '22I'), ('23D', '23D'), ('24A', '24A'), ('24F', '24F'), ('24I', '24I'), ('26', '26'), ('27', '27'), ('41B', '41B'), ('41D', '41D'), ('42B', '42B'), ('42C', '42C'), ('42D', '42D'), ('62B', '62B')], max_length=10, null=True)),
                ('route_path_coords', models.TextField(blank=True, help_text='JSON array of [[lat, lon], ...] points defining the route path. For Jeepneys.')),
                ('distance_km', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('travel_time_minutes', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('fare', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Route',
                'verbose_name_plural': 'Routes',
                'ordering': ['transport_type', 'code', 'origin'],
            },
        ),
        migrations.CreateModel(
            name='SavedRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, help_text='Session ID for anonymous users', max_length=255, null=True)),
                ('origin', models.CharField(max_length=255)),
                ('destination', models.CharField(max_length=255)),
                ('origin_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('origin_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('destination_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('destination_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('transport_type', models.CharField(max_length=50)),
                ('code', models.CharField(blank=True, max_length=10, null=True)),
                ('route_path_coords', models.TextField(blank=True)),
                ('distance_km', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('travel_time_minutes', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('fare', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('notes', models.TextField(blank=True)),
                ('saved_at', models.DateTimeField(auto_now_add=True)),
                ('last_used', models.DateTimeField(auto_now=True)),
                ('original_route', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='saved_by_users', to='route_input.route')),
                ('user', models.ForeignKey(blank=True, help_text='User who saved this route', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='saved_routes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Saved Route',
                'verbose_name_plural': 'Saved Routes',
                'ordering': ['-last_used'],
            },
        ),
    ]
