# Generated by Django 5.2.6 on 2025-10-02 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('route_input', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='route',
            name='optional_stops',
        ),
    ]
