# Generated by Django 5.2.6 on 2025-10-03 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('route_input', '0003_alter_route_options_route_code_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='route',
            options={'ordering': ['transport_type', 'code', 'origin']},
        ),
        migrations.AddField(
            model_name='route',
            name='distance_km',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Calculated distance in kilometers.', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='route',
            name='transport_type',
            field=models.CharField(choices=[('Jeepney', 'Jeepney'), ('Bus', 'Bus'), ('Taxi', 'Taxi'), ('Motorcycle', 'Motorcycle')], default='Jeepney', help_text='Type of transportation.', max_length=50),
        ),
        migrations.AddField(
            model_name='route',
            name='travel_time_minutes',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Calculated travel time in minutes.', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='route',
            name='code',
            field=models.CharField(blank=True, choices=[('01A', '01A'), ('01B', '01B'), ('01C', '01C'), ('01K', '01K'), ('02A', '02A'), ('02B', '02B'), ('03A', '03A'), ('03B', '03B'), ('03G', '03G'), ('03L', '03L'), ('03Q', '03Q'), ('04B', '04B'), ('04C', '04C'), ('04D', '04D'), ('04H', '04H'), ('04I', '04I'), ('04L', '04L'), ('04M', '04M'), ('06A', '06A'), ('06B', '06B'), ('06C', '06C'), ('06F', '06F'), ('06G', '06G'), ('06H', '06H'), ('07B', '07B'), ('07D', '07D'), ('08F', '08F'), ('08G', '08G'), ('09C', '09C'), ('09F', '09F'), ('09G', '09G'), ('10C', '10C'), ('10E', '10E'), ('10F', '10F'), ('10G', '10G'), ('10H', '10H'), ('10K', '10K'), ('10M', '10M'), ('11A', '11A'), ('11D', '11D'), ('12A', '12A'), ('12B', '12B'), ('12C', '12C'), ('12D', '12D'), ('12F', '12F'), ('12G', '12G'), ('12I', '12I'), ('12J', '12J'), ('12L', '12L'), ('13B', '13B'), ('13C', '13C'), ('13H', '13H'), ('14D', '14D'), ('15', '15'), ('17B', '17B'), ('17C', '17C'), ('17D', '17D'), ('20A', '20A'), ('20B', '20B'), ('21A', '21A'), ('21D', '21D'), ('22A', '22A'), ('22I', '22I'), ('23D', '23D'), ('24A', '24A'), ('24F', '24F'), ('24I', '24I'), ('26', '26'), ('27', '27'), ('41B', '41B'), ('41D', '41D'), ('42B', '42B'), ('42C', '42C'), ('42D', '42D'), ('62B', '62B')], help_text="Jeepney route code (e.g., '13C', '04L'). Required for Jeepney transport_type.", max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='route',
            name='destination',
            field=models.CharField(help_text='Text description of the destination location.', max_length=100),
        ),
        migrations.AlterField(
            model_name='route',
            name='destination_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Latitude for destination (auto-geocoded)', max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='route',
            name='destination_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Longitude for destination (auto-geocoded)', max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='route',
            name='fare',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Calculated estimated fare in PHP.', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='route',
            name='notes',
            field=models.TextField(blank=True, help_text="Any additional notes about the route, e.g., 'via Colon', 'morning rush only'."),
        ),
        migrations.AlterField(
            model_name='route',
            name='origin',
            field=models.CharField(help_text='Text description of the origin location.', max_length=100),
        ),
        migrations.AlterField(
            model_name='route',
            name='origin_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Latitude for origin (auto-geocoded or user-detected)', max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='route',
            name='origin_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Longitude for origin (auto-geocoded or user-detected)', max_digits=9, null=True),
        ),
    ]
