# Generated by Django 5.2.6 on 2025-10-03 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('route_input', '0005_alter_route_code_alter_route_destination_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='route',
            options={'ordering': ['transport_type', 'code', 'origin'], 'verbose_name': 'Route', 'verbose_name_plural': 'Routes'},
        ),
    ]
