# Generated by Django 5.2.6 on 2025-10-03 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('route_input', '0006_alter_route_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='destination',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='route',
            name='origin',
            field=models.CharField(max_length=255),
        ),
    ]
