# Generated by Django 5.2.6 on 2025-10-07 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('route_input', '0007_alter_route_destination_alter_route_origin'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='route_path_coords',
            field=models.TextField(blank=True, help_text='JSON array of [[lat, lon], ...] points defining the route path. For Jeepneys.'),
        ),
    ]
