# Generated by Django 5.2.7 on 2025-10-11 03:42

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('route_input', '0008_route_route_path_coords'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='SavedRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, help_text='Session ID for anonymous users', max_length=255, null=True)),
                ('origin', models.CharField(max_length=255)),
                ('destination', models.CharField(max_length=255)),
                ('origin_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('origin_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('destination_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('destination_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('transport_type', models.CharField(max_length=50)),
                ('code', models.CharField(blank=True, max_length=10, null=True)),
                ('route_path_coords', models.TextField(blank=True)),
                ('distance_km', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('travel_time_minutes', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('fare', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('notes', models.TextField(blank=True)),
                ('saved_at', models.DateTimeField(auto_now_add=True)),
                ('last_used', models.DateTimeField(auto_now=True)),
                ('original_route', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='saved_by_users', to='route_input.route')),
            ],
            options={
                'verbose_name': 'Saved Route',
                'verbose_name_plural': 'Saved Routes',
                'ordering': ['-last_used'],
            },
        ),
    ]
