# Generated by Django 5.2.7 on 2025-10-11 05:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('route_input', '0009_route_created_at_savedroute'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='savedroute',
            name='user',
            field=models.ForeignKey(blank=True, help_text='User who saved this route', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='saved_routes', to=settings.AUTH_USER_MODEL),
        ),
    ]
